import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Game Quiz",
  description: "Generated by create next app",
  icons: {
    icon: "/yt3.ggpht.com/AD07GBkLyMC3_DxAt2KIzDvthv3v8kYkwVeZuiX9WnrIO11fPC0rI3Jd6bbxXMKiMwkgfRrTaA=s176-c-k-c0x00ffffff-no-rj-mo"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
